version: '3'
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: vorto_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:password@postgres:5432?sslmode=disable"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data:
